/* Generated by Purgatory 2014-2016 */

package list.deep

import ch.epfl.data.sc.pardis
import pardis.ir._
import pardis.types.PardisTypeImplicits._
import pardis.effects._
import pardis.deep._
import pardis.deep.scalalib._
import pardis.deep.scalalib.collection._
import pardis.deep.scalalib.io._

import ch.epfl.data.sc.pardis.quasi.anf.{ BaseExt, BaseExtIR }
import ch.epfl.data.sc.pardis.quasi.TypeParameters.MaybeParamTag

trait ListDSLOps extends Base with ListOps with ScalaCoreOps with ch.epfl.data.sc.pardis.quasi.anf.BaseQuasiExp {  
  // Type representation
  val ListDSLType = ListDSLIRs.ListDSLType
  implicit val typeListDSL: TypeRep[ListDSL] = ListDSLType
  implicit class ListDSLRep(self : Rep[ListDSL]) {

  }
  object ListDSL {

  }
  // constructors

  // IR defs
  
  // method definitions
  
  type ListDSL = list.shallow.ListDSL
}
object ListDSLIRs extends Base {
  import ListIRs._
  import ScalaCoreIRs._
  // Type representation
  case object ListDSLType extends TypeRep[ListDSL] {
    def rebuild(newArguments: TypeRep[_]*): TypeRep[_] = ListDSLType
    val name = "ListDSL"
    val typeArguments = Nil
  }
      implicit val typeListDSL: TypeRep[ListDSL] = ListDSLType
  // case classes
  
  type ListDSL = list.shallow.ListDSL
}
trait ListDSLImplicits extends ListDSLOps { 
  // Add implicit conversions here!
}
trait ListDSLComponent extends ListDSLOps with ListDSLImplicits {  }

trait ListDSLPartialEvaluation extends ListDSLComponent with BasePartialEvaluation {  
  // Immutable field inlining 

  // Mutable field inlining 
  // Pure function partial evaluation
}


// QUASI GENERATED CODE:

object ListDSLQuasiNodes extends BaseExtIR {
  import ListDSLIRs._
  import ListQuasiNodes._
  import ScalaCoreQuasiNodes._
  // case classes
  type ListDSL = list.shallow.ListDSL
}

trait ListDSLExtOps extends BaseExt with ListExtOps with ScalaCoreExtOps with ch.epfl.data.sc.pardis.quasi.anf.BaseQuasiExt {
  
  import ListDSLQuasiNodes._
  import ch.epfl.data.sc.pardis.quasi.OverloadHackObj._
  import ListQuasiNodes._
  import ScalaCoreQuasiNodes._
  implicit class ListDSLRep(self : Rep[ListDSL]) {
  }
  object ListDSL {
  }
  // constructors
  
  // method definitions
  type ListDSL = list.shallow.ListDSL
}

abstract class ListDSLOpsPackaged extends ListDSLOps
abstract class ListDSLExtOpsPackaged extends ListDSLExtOps

